#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MicrosoftDynamicsAX2")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ClassDB.Properties.Settings.Default.MicrosoftDynamicsAX2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ESS_EmployeeInfoView2> ESS_EmployeeInfoView2s
		{
			get
			{
				return this.GetTable<ESS_EmployeeInfoView2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ESS_EmployeeInfoView2")]
	public partial class ESS_EmployeeInfoView2
	{
		
		private long _EmployeeID;
		
		private string _personnelnumber;
		
		private string _PASSWORD;
		
		private long _PERSON;
		
		private string _ArabicName;
		
		private string _EnglishName;
		
		private string _UserName;
		
		private int _ACTIVE;
		
		private decimal _BASICSALARY;
		
		private decimal _GOSISALARY;
		
		private decimal _GROSSSALARY;
		
		private string _CONTRACTCODE;
		
		private int _CONTRACTTYPE;
		
		private System.DateTime _contractStart;
		
		private System.DateTime _contractEnd;
		
		private System.DateTime _JOININGDATE;
		
		private decimal _NOOFYEARS;
		
		private System.DateTime _BIRTHDATE;
		
		private string _EDUCATION;
		
		private string _NATIONALITY;
		
		private string _RELGION;
		
		private string _SPONSERSHIP;
		
		private int _STATUS;
		
		private int _GenderID;
		
		private string _GENDERName;
		
		private System.Nullable<long> _ManagerID;
		
		private string _DirectManagerName;
		
		private string _Email;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Company;
		
		private int _IsManager;
		
		private int _IsDepartmentManager;
		
		private int _VacationBalance;
		
		private int _WORKERGROUP;
		
		private System.Nullable<long> _DepartmentID;
		
		private string _DepartmentName;
		
		private System.Nullable<System.DateTime> _iqamaDate;
		
		private System.Nullable<System.DateTime> _iqamaExpiryDate;
		
		private string _IqamaID;
		
		private System.DateTime _lastReturnVacationDate;
		
		private string _position;
		
		private System.Nullable<long> _positionID;
		
		private string _PROFILEID;
		
		public ESS_EmployeeInfoView2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="BigInt NOT NULL")]
		public long EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this._EmployeeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personnelnumber", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string personnelnumber
		{
			get
			{
				return this._personnelnumber;
			}
			set
			{
				if ((this._personnelnumber != value))
				{
					this._personnelnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSON", DbType="BigInt NOT NULL")]
		public long PERSON
		{
			get
			{
				return this._PERSON;
			}
			set
			{
				if ((this._PERSON != value))
				{
					this._PERSON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArabicName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ArabicName
		{
			get
			{
				return this._ArabicName;
			}
			set
			{
				if ((this._ArabicName != value))
				{
					this._ArabicName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnglishName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EnglishName
		{
			get
			{
				return this._EnglishName;
			}
			set
			{
				if ((this._EnglishName != value))
				{
					this._EnglishName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(80)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVE", DbType="Int NOT NULL")]
		public int ACTIVE
		{
			get
			{
				return this._ACTIVE;
			}
			set
			{
				if ((this._ACTIVE != value))
				{
					this._ACTIVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASICSALARY", DbType="Decimal(32,16) NOT NULL")]
		public decimal BASICSALARY
		{
			get
			{
				return this._BASICSALARY;
			}
			set
			{
				if ((this._BASICSALARY != value))
				{
					this._BASICSALARY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOSISALARY", DbType="Decimal(32,16) NOT NULL")]
		public decimal GOSISALARY
		{
			get
			{
				return this._GOSISALARY;
			}
			set
			{
				if ((this._GOSISALARY != value))
				{
					this._GOSISALARY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROSSSALARY", DbType="Decimal(32,16) NOT NULL")]
		public decimal GROSSSALARY
		{
			get
			{
				return this._GROSSSALARY;
			}
			set
			{
				if ((this._GROSSSALARY != value))
				{
					this._GROSSSALARY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRACTCODE", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string CONTRACTCODE
		{
			get
			{
				return this._CONTRACTCODE;
			}
			set
			{
				if ((this._CONTRACTCODE != value))
				{
					this._CONTRACTCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRACTTYPE", DbType="Int NOT NULL")]
		public int CONTRACTTYPE
		{
			get
			{
				return this._CONTRACTTYPE;
			}
			set
			{
				if ((this._CONTRACTTYPE != value))
				{
					this._CONTRACTTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contractStart", DbType="DateTime NOT NULL")]
		public System.DateTime contractStart
		{
			get
			{
				return this._contractStart;
			}
			set
			{
				if ((this._contractStart != value))
				{
					this._contractStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contractEnd", DbType="DateTime NOT NULL")]
		public System.DateTime contractEnd
		{
			get
			{
				return this._contractEnd;
			}
			set
			{
				if ((this._contractEnd != value))
				{
					this._contractEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOININGDATE", DbType="DateTime NOT NULL")]
		public System.DateTime JOININGDATE
		{
			get
			{
				return this._JOININGDATE;
			}
			set
			{
				if ((this._JOININGDATE != value))
				{
					this._JOININGDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOOFYEARS", DbType="Decimal(32,16) NOT NULL")]
		public decimal NOOFYEARS
		{
			get
			{
				return this._NOOFYEARS;
			}
			set
			{
				if ((this._NOOFYEARS != value))
				{
					this._NOOFYEARS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDATE", DbType="DateTime NOT NULL")]
		public System.DateTime BIRTHDATE
		{
			get
			{
				return this._BIRTHDATE;
			}
			set
			{
				if ((this._BIRTHDATE != value))
				{
					this._BIRTHDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDUCATION", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string EDUCATION
		{
			get
			{
				return this._EDUCATION;
			}
			set
			{
				if ((this._EDUCATION != value))
				{
					this._EDUCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONALITY", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string NATIONALITY
		{
			get
			{
				return this._NATIONALITY;
			}
			set
			{
				if ((this._NATIONALITY != value))
				{
					this._NATIONALITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELGION", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string RELGION
		{
			get
			{
				return this._RELGION;
			}
			set
			{
				if ((this._RELGION != value))
				{
					this._RELGION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPONSERSHIP", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string SPONSERSHIP
		{
			get
			{
				return this._SPONSERSHIP;
			}
			set
			{
				if ((this._SPONSERSHIP != value))
				{
					this._SPONSERSHIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int NOT NULL")]
		public int STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderID", DbType="Int NOT NULL")]
		public int GenderID
		{
			get
			{
				return this._GenderID;
			}
			set
			{
				if ((this._GenderID != value))
				{
					this._GenderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDERName", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string GENDERName
		{
			get
			{
				return this._GENDERName;
			}
			set
			{
				if ((this._GENDERName != value))
				{
					this._GENDERName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerID", DbType="BigInt")]
		public System.Nullable<long> ManagerID
		{
			get
			{
				return this._ManagerID;
			}
			set
			{
				if ((this._ManagerID != value))
				{
					this._ManagerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectManagerName", DbType="NVarChar(MAX)")]
		public string DirectManagerName
		{
			get
			{
				return this._DirectManagerName;
			}
			set
			{
				if ((this._DirectManagerName != value))
				{
					this._DirectManagerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(255)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(255)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsManager", DbType="Int NOT NULL")]
		public int IsManager
		{
			get
			{
				return this._IsManager;
			}
			set
			{
				if ((this._IsManager != value))
				{
					this._IsManager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDepartmentManager", DbType="Int NOT NULL")]
		public int IsDepartmentManager
		{
			get
			{
				return this._IsDepartmentManager;
			}
			set
			{
				if ((this._IsDepartmentManager != value))
				{
					this._IsDepartmentManager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacationBalance", DbType="Int NOT NULL")]
		public int VacationBalance
		{
			get
			{
				return this._VacationBalance;
			}
			set
			{
				if ((this._VacationBalance != value))
				{
					this._VacationBalance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKERGROUP", DbType="Int NOT NULL")]
		public int WORKERGROUP
		{
			get
			{
				return this._WORKERGROUP;
			}
			set
			{
				if ((this._WORKERGROUP != value))
				{
					this._WORKERGROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="BigInt")]
		public System.Nullable<long> DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this._DepartmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentName", DbType="NVarChar(MAX)")]
		public string DepartmentName
		{
			get
			{
				return this._DepartmentName;
			}
			set
			{
				if ((this._DepartmentName != value))
				{
					this._DepartmentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iqamaDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> iqamaDate
		{
			get
			{
				return this._iqamaDate;
			}
			set
			{
				if ((this._iqamaDate != value))
				{
					this._iqamaDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iqamaExpiryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> iqamaExpiryDate
		{
			get
			{
				return this._iqamaExpiryDate;
			}
			set
			{
				if ((this._iqamaExpiryDate != value))
				{
					this._iqamaExpiryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaID", DbType="NVarChar(15)")]
		public string IqamaID
		{
			get
			{
				return this._IqamaID;
			}
			set
			{
				if ((this._IqamaID != value))
				{
					this._IqamaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastReturnVacationDate", DbType="DateTime NOT NULL")]
		public System.DateTime lastReturnVacationDate
		{
			get
			{
				return this._lastReturnVacationDate;
			}
			set
			{
				if ((this._lastReturnVacationDate != value))
				{
					this._lastReturnVacationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="NVarChar(MAX)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_positionID", DbType="BigInt")]
		public System.Nullable<long> positionID
		{
			get
			{
				return this._positionID;
			}
			set
			{
				if ((this._positionID != value))
				{
					this._positionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILEID", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string PROFILEID
		{
			get
			{
				return this._PROFILEID;
			}
			set
			{
				if ((this._PROFILEID != value))
				{
					this._PROFILEID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
