//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESSEntities : DbContext
    {
        public ESSEntities()
            : base("name=ESSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ESS_ClearanceTypes> ESS_ClearanceTypes { get; set; }
        public virtual DbSet<ESS_EmailsNotificationsLogs> ESS_EmailsNotificationsLogs { get; set; }
        public virtual DbSet<ESS_HR_EmployeeClearance> ESS_HR_EmployeeClearance { get; set; }
        public virtual DbSet<ESS_MEDICALINSURANCETypes> ESS_MEDICALINSURANCETypes { get; set; }
        public virtual DbSet<ESS_WF_OrderStage> ESS_WF_OrderStage { get; set; }
        public virtual DbSet<ESS_AdministratorIntedabReason> ESS_AdministratorIntedabReason { get; set; }
        public virtual DbSet<ESS_AmendmentReasons> ESS_AmendmentReasons { get; set; }
        public virtual DbSet<ESS_Attachments> ESS_Attachments { get; set; }
        public virtual DbSet<ESS_ClearanceLetterType> ESS_ClearanceLetterType { get; set; }
        public virtual DbSet<ESS_Documents> ESS_Documents { get; set; }
        public virtual DbSet<ESS_Emp> ESS_Emp { get; set; }
        public virtual DbSet<ESS_ExitReEntryVisaReasons> ESS_ExitReEntryVisaReasons { get; set; }
        public virtual DbSet<ESS_ExternalCommitment> ESS_ExternalCommitment { get; set; }
        public virtual DbSet<ESS_Family> ESS_Family { get; set; }
        public virtual DbSet<ESS_FamilyVisit> ESS_FamilyVisit { get; set; }
        public virtual DbSet<ESS_Groups> ESS_Groups { get; set; }
        public virtual DbSet<ESS_GroupsMembers> ESS_GroupsMembers { get; set; }
        public virtual DbSet<ESS_Houseing> ESS_Houseing { get; set; }
        public virtual DbSet<ESS_HR_Amendment> ESS_HR_Amendment { get; set; }
        public virtual DbSet<ESS_HRAnnouncement> ESS_HRAnnouncement { get; set; }
        public virtual DbSet<ESS_HRAnnouncementAlert> ESS_HRAnnouncementAlert { get; set; }
        public virtual DbSet<ESS_HR_ChangeHouseingRequest> ESS_HR_ChangeHouseingRequest { get; set; }
        public virtual DbSet<ESS_HR_EOS> ESS_HR_EOS { get; set; }
        public virtual DbSet<ESS_HR_Evaluation> ESS_HR_Evaluation { get; set; }
        public virtual DbSet<ESS_HR_ExitRentryVisa> ESS_HR_ExitRentryVisa { get; set; }
        public virtual DbSet<ESS_HR_Leave> ESS_HR_Leave { get; set; }
        public virtual DbSet<ESS_HR_MEDICALINSURANCE> ESS_HR_MEDICALINSURANCE { get; set; }
        public virtual DbSet<ESS_HR_VactionResubmittion> ESS_HR_VactionResubmittion { get; set; }
        public virtual DbSet<ESS_LetterRequests> ESS_LetterRequests { get; set; }
        public virtual DbSet<ESS_Relevant> ESS_Relevant { get; set; }
        public virtual DbSet<ESS_Requests> ESS_Requests { get; set; }
        public virtual DbSet<ESS_Skills> ESS_Skills { get; set; }
        public virtual DbSet<ESS_Status> ESS_Status { get; set; }
        public virtual DbSet<ESS_Tasks> ESS_Tasks { get; set; }
        public virtual DbSet<Ess_TravelingMethods> Ess_TravelingMethods { get; set; }
        public virtual DbSet<ESS_Trip> ESS_Trip { get; set; }
        public virtual DbSet<ESS_VactionTypes> ESS_VactionTypes { get; set; }
    }
}
