//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_WF_OrderStage
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int StageTypeID { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Note { get; set; }
        public string ActionName { get; set; }
    
        public virtual ESS_Documents ESS_Documents { get; set; }
    }
}
