//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_ExternalCommitment
    {
        public int ID { get; set; }
        public Nullable<int> ClearanceLetterType { get; set; }
        public string MinistryName { get; set; }
        public string End_Date { get; set; }
        public string Remarkes { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual ESS_ClearanceLetterType ESS_ClearanceLetterType { get; set; }
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
    }
}
