//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_HR_Amendment
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> MonthYear { get; set; }
        public Nullable<int> MonthDate { get; set; }
        public Nullable<int> MonthDay { get; set; }
        public string Description { get; set; }
        public Nullable<int> AmendReason { get; set; }
        public string Time { get; set; }
        public Nullable<bool> ISDirectMgrApprove { get; set; }
        public Nullable<bool> ISDepartmentMgrApprove { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public string Type { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> Recorded { get; set; }
    
        public virtual ESS_AmendmentReasons ESS_AmendmentReasons { get; set; }
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
        public virtual ESS_Requests ESS_Requests { get; set; }
    }
}
