//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_GroupsMembers
    {
        public int GroupMemberID { get; set; }
        public int GroupId { get; set; }
        public string MemberName { get; set; }
        public string MemberShabId { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
    
        public virtual ESS_Groups ESS_Groups { get; set; }
    }
}
