//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_HR_Leave
    {
        public int ID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string VacationTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DaysNo { get; set; }
        public string Discrebtion { get; set; }
        public Nullable<int> TravelMethodID { get; set; }
        public string AirLineType { get; set; }
        public Nullable<System.DateTime> DepatureDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> VisaTypeID { get; set; }
        public Nullable<System.DateTime> VisaFromDate { get; set; }
        public Nullable<System.DateTime> VisaToDate { get; set; }
        public string ReplacmentStuff { get; set; }
        public Nullable<int> LeavePaymentTypeID { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> Recorded { get; set; }
        public Nullable<long> ReplacmentStuffID { get; set; }
        public Nullable<long> ReplacmentStuffIDIsApprove { get; set; }
    
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
        public virtual ESS_Requests ESS_Requests { get; set; }
    }
}
