//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_HR_EOS
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string EOSType { get; set; }
        public string Reasons { get; set; }
        public string ApprovedLetterFilePath { get; set; }
        public string ApprovedLetterFileName { get; set; }
        public string EOSClearanceFilePath { get; set; }
        public string EOSClearanceFileName { get; set; }
        public Nullable<int> RequesTypeID { get; set; }
        public Nullable<System.DateTime> LastWorkingDateBFNotice { get; set; }
        public Nullable<System.DateTime> LastWorkingDateInNotice { get; set; }
        public Nullable<bool> Recorded { get; set; }
    
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
        public virtual ESS_Requests ESS_Requests { get; set; }
    }
}
