//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_HR_MEDICALINSURANCE
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> TypeOFRequestID { get; set; }
        public string OtherType { get; set; }
        public string MembershipNO { get; set; }
        public string MemberName { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> IDExpireDate { get; set; }
        public Nullable<bool> IsDependents { get; set; }
        public string RelationshipID { get; set; }
        public string CurrentHealthCare { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    
        public virtual ESS_MEDICALINSURANCETypes ESS_MEDICALINSURANCETypes { get; set; }
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
        public virtual ESS_Requests ESS_Requests { get; set; }
    }
}
