//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESS_Documents()
        {
            this.ESS_HR_EmployeeClearance = new HashSet<ESS_HR_EmployeeClearance>();
            this.ESS_WF_OrderStage = new HashSet<ESS_WF_OrderStage>();
            this.ESS_ExternalCommitment = new HashSet<ESS_ExternalCommitment>();
            this.ESS_FamilyVisit = new HashSet<ESS_FamilyVisit>();
            this.ESS_Houseing = new HashSet<ESS_Houseing>();
            this.ESS_HR_Amendment = new HashSet<ESS_HR_Amendment>();
            this.ESS_HR_ChangeHouseingRequest = new HashSet<ESS_HR_ChangeHouseingRequest>();
            this.ESS_HR_EOS = new HashSet<ESS_HR_EOS>();
            this.ESS_HR_ExitRentryVisa = new HashSet<ESS_HR_ExitRentryVisa>();
            this.ESS_HR_Leave = new HashSet<ESS_HR_Leave>();
            this.ESS_HR_MEDICALINSURANCE = new HashSet<ESS_HR_MEDICALINSURANCE>();
            this.ESS_HR_VactionResubmittion = new HashSet<ESS_HR_VactionResubmittion>();
            this.ESS_LetterRequests = new HashSet<ESS_LetterRequests>();
            this.ESS_Trip = new HashSet<ESS_Trip>();
        }
    
        public int ID { get; set; }
        public long ShabId { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> AsignedID { get; set; }
        public Nullable<System.DateTime> AsignedDate { get; set; }
        public Nullable<long> DirectMGRID { get; set; }
        public Nullable<System.DateTime> DirectManagerAsignedDate { get; set; }
        public Nullable<System.DateTime> DirectManagerApproveDate { get; set; }
        public Nullable<long> DepMgrID { get; set; }
        public Nullable<System.DateTime> DepMgrAsignedDate { get; set; }
        public Nullable<System.DateTime> DepMgrApproveDate { get; set; }
        public string DirectMgrComment { get; set; }
        public string DepMgrComment { get; set; }
        public string HrReviewComment { get; set; }
        public Nullable<System.DateTime> HrReviewAsignedDate { get; set; }
        public Nullable<System.DateTime> HrReviewApproveDate { get; set; }
        public Nullable<long> HrReviewID { get; set; }
        public Nullable<System.DateTime> HrSuperVisorAsignedDate { get; set; }
        public Nullable<System.DateTime> HrSuperVisorApproveDate { get; set; }
        public Nullable<long> HrSuperVisorID { get; set; }
        public string HrSuperVisorComment { get; set; }
        public Nullable<System.DateTime> HrDepMgrAsignedDate { get; set; }
        public Nullable<System.DateTime> HrDepMgrApproveDate { get; set; }
        public Nullable<long> HrDepMgrID { get; set; }
        public string HrDepMgrComment { get; set; }
        public string FinReviewComment { get; set; }
        public Nullable<System.DateTime> FinReviewApproveDate { get; set; }
        public Nullable<long> FinReviewID { get; set; }
        public Nullable<System.DateTime> FinSuperVisorAsignedDate { get; set; }
        public Nullable<System.DateTime> FinSuperVisorApproveDate { get; set; }
        public Nullable<int> FinSuperVisorID { get; set; }
        public string FinSuperVisorComment { get; set; }
        public Nullable<System.DateTime> FinDepMgrAsignedDate { get; set; }
        public Nullable<System.DateTime> FinDepMgrApproveDate { get; set; }
        public Nullable<int> FinDepMgrID { get; set; }
        public string FinDepMgrComment { get; set; }
        public Nullable<bool> Recorded { get; set; }
        public Nullable<bool> IsDelegate { get; set; }
        public Nullable<bool> IsDelegateApprove { get; set; }
        public Nullable<long> DelegateFromID { get; set; }
        public Nullable<long> DelegateToID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_EmployeeClearance> ESS_HR_EmployeeClearance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_WF_OrderStage> ESS_WF_OrderStage { get; set; }
        public virtual ESS_Requests ESS_Requests { get; set; }
        public virtual ESS_Status ESS_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_ExternalCommitment> ESS_ExternalCommitment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_FamilyVisit> ESS_FamilyVisit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Houseing> ESS_Houseing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_Amendment> ESS_HR_Amendment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_ChangeHouseingRequest> ESS_HR_ChangeHouseingRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_EOS> ESS_HR_EOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_ExitRentryVisa> ESS_HR_ExitRentryVisa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_Leave> ESS_HR_Leave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_MEDICALINSURANCE> ESS_HR_MEDICALINSURANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_VactionResubmittion> ESS_HR_VactionResubmittion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_LetterRequests> ESS_LetterRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Trip> ESS_Trip { get; set; }
    }
}
