//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_Relevant
    {
        public int ID { get; set; }
        public string Relevant { get; set; }
        public int FamilyID { get; set; }
    
        public virtual ESS_FamilyVisit ESS_FamilyVisit { get; set; }
    }
}
