//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_LetterRequests
    {
        public int ID { get; set; }
        public string LetterType { get; set; }
        public string Justifiction { get; set; }
        public string Other { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string OrganizationAR { get; set; }
        public string OrganizationEN { get; set; }
        public Nullable<System.DateTime> LetterDate { get; set; }
    
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
    }
}
