//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_EmailsNotificationsLogs
    {
        public long NotificationID { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public string NotificationText { get; set; }
        public string NotificationTitle { get; set; }
        public long FromEmpID { get; set; }
        public string FromEmail { get; set; }
        public Nullable<long> ToEmpID { get; set; }
        public string ToEmpEmail { get; set; }
        public long RequestID { get; set; }
        public long RequestTypeID { get; set; }
        public bool NotificationStatus { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
    }
}
