//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_MEDICALINSURANCETypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESS_MEDICALINSURANCETypes()
        {
            this.ESS_HR_MEDICALINSURANCE = new HashSet<ESS_HR_MEDICALINSURANCE>();
        }
    
        public int ID { get; set; }
        public string TypeEN { get; set; }
        public string TypeAR { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_MEDICALINSURANCE> ESS_HR_MEDICALINSURANCE { get; set; }
    }
}
