//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESS_Requests()
        {
            this.ESS_HR_EmployeeClearance = new HashSet<ESS_HR_EmployeeClearance>();
            this.ESS_Attachments = new HashSet<ESS_Attachments>();
            this.ESS_Documents = new HashSet<ESS_Documents>();
            this.ESS_HR_Amendment = new HashSet<ESS_HR_Amendment>();
            this.ESS_HR_ChangeHouseingRequest = new HashSet<ESS_HR_ChangeHouseingRequest>();
            this.ESS_HR_EOS = new HashSet<ESS_HR_EOS>();
            this.ESS_HR_ExitRentryVisa = new HashSet<ESS_HR_ExitRentryVisa>();
            this.ESS_HR_Leave = new HashSet<ESS_HR_Leave>();
            this.ESS_HR_MEDICALINSURANCE = new HashSet<ESS_HR_MEDICALINSURANCE>();
            this.ESS_HR_VactionResubmittion = new HashSet<ESS_HR_VactionResubmittion>();
        }
    
        public int id { get; set; }
        public string Department { get; set; }
        public string Requests { get; set; }
        public string DetailsURL { get; set; }
        public string RequestUrl { get; set; }
        public Nullable<int> RequestGroupID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string icons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_EmployeeClearance> ESS_HR_EmployeeClearance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Attachments> ESS_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Documents> ESS_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_Amendment> ESS_HR_Amendment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_ChangeHouseingRequest> ESS_HR_ChangeHouseingRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_EOS> ESS_HR_EOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_ExitRentryVisa> ESS_HR_ExitRentryVisa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_Leave> ESS_HR_Leave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_MEDICALINSURANCE> ESS_HR_MEDICALINSURANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_VactionResubmittion> ESS_HR_VactionResubmittion { get; set; }
    }
}
