//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_Houseing
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string HouseingDetails { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> MonthlyInstallment { get; set; }
        public Nullable<int> NoOfInstallment { get; set; }
        public string FilePath { get; set; }
        public string ContractPeriod { get; set; }
        public Nullable<System.DateTime> LoanStartDate { get; set; }
        public Nullable<bool> Recorded { get; set; }
        public string LOANTYPECODE { get; set; }
    
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
    }
}
