//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_HR_ChangeHouseingRequest
    {
        public int ID { get; set; }
        public Nullable<int> DocID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RequesTypeID { get; set; }
        public string Description { get; set; }
    
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
        public virtual ESS_Requests ESS_Requests { get; set; }
    }
}
