//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_HR_VactionResubmittion
    {
        public int ID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> VacationTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DaysNo { get; set; }
        public string Discrebtion { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<int> VactionID { get; set; }
        public Nullable<bool> Delay { get; set; }
        public Nullable<System.DateTime> ActualResubmittionDate { get; set; }
    
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
        public virtual ESS_Requests ESS_Requests { get; set; }
        public virtual ESS_VactionTypes ESS_VactionTypes { get; set; }
    }
}
