//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_Emp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESS_Emp()
        {
            this.ESS_HR_EmployeeClearance = new HashSet<ESS_HR_EmployeeClearance>();
            this.ESS_Attachments = new HashSet<ESS_Attachments>();
            this.ESS_ExternalCommitment = new HashSet<ESS_ExternalCommitment>();
            this.ESS_FamilyVisit = new HashSet<ESS_FamilyVisit>();
            this.ESS_Houseing = new HashSet<ESS_Houseing>();
            this.ESS_HR_Amendment = new HashSet<ESS_HR_Amendment>();
            this.ESS_HR_ChangeHouseingRequest = new HashSet<ESS_HR_ChangeHouseingRequest>();
            this.ESS_HR_EOS = new HashSet<ESS_HR_EOS>();
            this.ESS_HR_Evaluation = new HashSet<ESS_HR_Evaluation>();
            this.ESS_HR_Evaluation1 = new HashSet<ESS_HR_Evaluation>();
            this.ESS_HR_ExitRentryVisa = new HashSet<ESS_HR_ExitRentryVisa>();
            this.ESS_HR_Leave = new HashSet<ESS_HR_Leave>();
            this.ESS_HR_MEDICALINSURANCE = new HashSet<ESS_HR_MEDICALINSURANCE>();
            this.ESS_Trip = new HashSet<ESS_Trip>();
            this.ESS_HR_VactionResubmittion = new HashSet<ESS_HR_VactionResubmittion>();
            this.ESS_LetterRequests = new HashSet<ESS_LetterRequests>();
            this.ESS_Trip1 = new HashSet<ESS_Trip>();
            this.ESS_Skills = new HashSet<ESS_Skills>();
        }
    
        public int ID { get; set; }
        public string EmpName { get; set; }
        public string EmpShabID { get; set; }
        public string EmpDepartment { get; set; }
        public Nullable<System.DateTime> EmpJoinDate { get; set; }
        public Nullable<System.DateTime> IqamaExpDate { get; set; }
        public string ContractPeriod { get; set; }
        public string JobLocation { get; set; }
        public string Position { get; set; }
        public string VacationProfile { get; set; }
        public string VacationBalance { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public Nullable<bool> IsDepartmentManager { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<long> DirectManagerID { get; set; }
        public Nullable<long> ShabID { get; set; }
        public Nullable<int> HousingAmount { get; set; }
        public Nullable<System.DateTime> LastReturnVacationDate { get; set; }
        public Nullable<System.DateTime> ContractFromDate { get; set; }
        public Nullable<System.DateTime> ContractToDate { get; set; }
        public string EmpEmail { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<bool> IsDataComplete { get; set; }
        public Nullable<bool> IsMarried { get; set; }
        public Nullable<bool> IsSaudi { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_EmployeeClearance> ESS_HR_EmployeeClearance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Attachments> ESS_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_ExternalCommitment> ESS_ExternalCommitment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_FamilyVisit> ESS_FamilyVisit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Houseing> ESS_Houseing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_Amendment> ESS_HR_Amendment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_ChangeHouseingRequest> ESS_HR_ChangeHouseingRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_EOS> ESS_HR_EOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_Evaluation> ESS_HR_Evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_Evaluation> ESS_HR_Evaluation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_ExitRentryVisa> ESS_HR_ExitRentryVisa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_Leave> ESS_HR_Leave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_MEDICALINSURANCE> ESS_HR_MEDICALINSURANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Trip> ESS_Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_HR_VactionResubmittion> ESS_HR_VactionResubmittion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_LetterRequests> ESS_LetterRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Trip> ESS_Trip1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESS_Skills> ESS_Skills { get; set; }
    }
}
