//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESS_Trip
    {
        public int ID { get; set; }
        public int DocumentID { get; set; }
        public int EmpID { get; set; }
        public int RequestID { get; set; }
        public string TRIPTYPEID { get; set; }
        public string FromCountry { get; set; }
        public string FromCITY { get; set; }
        public string ToCountry { get; set; }
        public string ToCITY { get; set; }
        public System.DateTime FromDATE { get; set; }
        public System.DateTime ToDATE { get; set; }
        public int DAY { get; set; }
        public int ISNEEDVISA { get; set; }
        public string VisaType { get; set; }
        public string VISANUMBER { get; set; }
        public System.DateTime VisaFromDate { get; set; }
        public System.DateTime VisaToDate { get; set; }
        public int ISTAKERENTCOMPANYLETTER { get; set; }
        public int ISPROJECT { get; set; }
        public string PROJID { get; set; }
        public decimal ADVANCPAYMENT { get; set; }
        public int TravelMethod { get; set; }
        public string AirLineName { get; set; }
        public System.DateTime TICKETDEPARTUREDATE { get; set; }
        public System.DateTime TICKETRETURNDATE { get; set; }
        public System.DateTime DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string REASONCOMMENT { get; set; }
        public int TICKETDEPARTUREDATETZID { get; set; }
        public int TICKETRETURNDATETZID { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public int VALIDATED { get; set; }
        public long WORKER { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public string CREATEDBY { get; set; }
        public decimal TICKETAMOUNT { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    
        public virtual ESS_Documents ESS_Documents { get; set; }
        public virtual ESS_Emp ESS_Emp { get; set; }
        public virtual ESS_Emp ESS_Emp1 { get; set; }
    }
}
